# Generated by Django 3.1.6 on 2022-11-19 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_profile', serialize=False, to='auth.user')),
                ('nickname', models.CharField(default='Unknown', max_length=20)),
                ('icon', models.IntegerField(default=0)),
            ],
        ),
    ]
