# Generated by Django 3.1.6 on 2022-11-19 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupcode', models.CharField(default='wrong', max_length=10)),
                ('title', models.CharField(max_length=10, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('event', models.IntegerField(default=0)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('text', models.CharField(default='', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=10)),
                ('size', models.IntegerField(default=1)),
                ('period', models.IntegerField(default=3)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_room', to='rooms.group')),
            ],
        ),
    ]
