# Generated by Django 3.1.6 on 2022-11-19 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_room', to='users.profile'),
        ),
        migrations.AddField(
            model_name='history',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_history', to='users.profile'),
        ),
        migrations.AddField(
            model_name='history',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_history', to='rooms.room'),
        ),
        migrations.AddField(
            model_name='group',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_group', to='users.profile'),
        ),
        migrations.AddField(
            model_name='group',
            name='member',
            field=models.ManyToManyField(blank=True, related_name='members_group', to='users.Profile'),
        ),
        migrations.AddField(
            model_name='group',
            name='memberinvite',
            field=models.ManyToManyField(blank=True, related_name='invited', to='users.Profile'),
        ),
    ]
