# Generated by Django 3.1.6 on 2022-11-19 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('rooms', '0002_auto_20221119_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='member',
            field=models.ManyToManyField(blank=True, related_name='member_group', to='users.Profile'),
        ),
    ]
