# Generated by Django 3.1.6 on 2022-11-19 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_auto_20221119_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='image',
            field=models.ImageField(null=True, upload_to='post/'),
        ),
    ]
