# Generated by Django 3.1.6 on 2022-11-19 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_room_last_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='last_history',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_room', to='rooms.history'),
        ),
    ]
