# Generated by Django 3.1.6 on 2022-11-19 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_state_message'),
        ('rooms', '0006_auto_20221119_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('score', models.IntegerField(default=0)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_statics', to='rooms.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_statics', to='users.profile')),
            ],
        ),
        migrations.AddConstraint(
            model_name='statics',
            constraint=models.UniqueConstraint(fields=('user', 'room'), name='statics_usergroup_unique'),
        ),
    ]
